title: ExperienceAI Challenge | Stage 1 | What is Machine Learning?
hero_image: images/banner.png
description: In this first stage of the ExperimentAI Music quest, you will explore AI by playing with some fun apps which use machine learning, creating your first machine learning model and thinking about who uses AI, where it exists and how it can improve your life.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Welcome!
  - title: Introduction
  - title: What is AI and Machine Learning?
  - title: Play with predictive AI
  - title: Make a machine learning model
  - title: What next?
