title: ExperienceAI Challenge | Stage 1 | What is machine learning?
hero_image: images/banner.png
description: In the first stage of the ExperimentAI Challenge, you will explore AI by playing with some fun apps that use machine learning (an approach taken to create AI applications). Next, you'll create your first machine learning model and think about who will use your AI application and how it can improve their life. You'll also pick which kind of data your application will classify - text, audio, or images.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Welcome!
  - title: Introduction
  - title: What is AI and machine learning?
  - title: Play with predictive AI
  - title: Make a machine learning model
  - title: What next?
