title: ExperienceAI Challenge | Stage 1 | What is Machine Learning?
hero_image: images/banner.png
description: In this first stage of the ExperimentAI Challenge, you will explore AI by playing with some fun apps which use Machine Learning (an approach taken to create AI applications), creating your first machine learning model and thinking about who will use your AI application and how it can improve their life. You'll also need to pick which kind of data your application will classify - numbers, text, audio or images.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Welcome!
  - title: Introduction
  - title: What is AI and Machine Learning?
  - title: Play with predictive AI
  - title: Make a machine learning model
  - title: What next?
